"""Add financial_institutions table

Revision ID: 29425a472fc3
Revises: 
Create Date: 2026-01-07 14:15:37.634201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.security
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29425a472fc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SME', 'FI', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('financial_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('fi_type', sa.Enum('BANK', 'FUND', 'FINTECH', name='fitype'), nullable=False),
    sa.Column('contact_person_name', app.core.security.EncryptedString(), nullable=True),
    sa.Column('contact_phone', app.core.security.EncryptedString(), nullable=True),
    sa.Column('risk_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_financial_institutions_id'), 'financial_institutions', ['id'], unique=False)
    op.create_table('smes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('legal_rep_name', app.core.security.EncryptedString(), nullable=False),
    sa.Column('legal_rep_cccd', app.core.security.EncryptedString(), nullable=False),
    sa.Column('phone_number', app.core.security.EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_smes_id'), 'smes', ['id'], unique=False)
    op.create_index(op.f('ix_smes_tax_code'), 'smes', ['tax_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smes_tax_code'), table_name='smes')
    op.drop_index(op.f('ix_smes_id'), table_name='smes')
    op.drop_table('smes')
    op.drop_index(op.f('ix_financial_institutions_id'), table_name='financial_institutions')
    op.drop_table('financial_institutions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
