"""Add status and nullable sepay_id to BankTransaction

Revision ID: 3404caf0be35
Revises: 597fc70c0c3f
Create Date: 2026-01-10 02:58:32.568352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3404caf0be35'
down_revision: Union[str, Sequence[str], None] = '597fc70c0c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('status', sa.String(length=20), nullable=False, server_default='SUCCESS'))
    op.add_column('bank_transactions', sa.Column('related_invoice_id', sa.Integer(), nullable=True))
    op.alter_column('bank_transactions', 'sepay_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transactions', 'sepay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bank_transactions', 'related_invoice_id')
    op.drop_column('bank_transactions', 'status')
    # ### end Alembic commands ###
