"""Add bank_accounts table

Revision ID: 350b5abb2d3d
Revises: 8a7cf38c8eb2
Create Date: 2026-01-09 09:58:10.951191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350b5abb2d3d'
down_revision: Union[str, Sequence[str], None] = '8a7cf38c8eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
