"""Refactor Offer and InvoiceStatus

Revision ID: 597fc70c0c3f
Revises: 42795e0c3b69
Create Date: 2026-01-10 02:24:37.153642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597fc70c0c3f'
down_revision: Union[str, Sequence[str], None] = '42795e0c3b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('fi_disbursement_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('offers', sa.Column('platform_commission_from_fi', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('offers', sa.Column('net_to_fi', sa.DECIMAL(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'net_to_fi')
    op.drop_column('offers', 'platform_commission_from_fi')
    op.drop_column('offers', 'fi_disbursement_amount')
    # ### end Alembic commands ###
