"""Fix InvoiceStatus Enum

Revision ID: 87a6d76130fb
Revises: 3404caf0be35
Create Date: 2026-01-10 03:09:29.370620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a6d76130fb'
down_revision: Union[str, Sequence[str], None] = '3404caf0be35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Fix for Postgres Enum
    op.execute("ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'FUNDING_RECEIVED'")
    op.execute("ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'REPAYMENT_RECEIVED'")
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
