"""Add KYC fields to SME

Revision ID: a2a9aff11f69
Revises: 350b5abb2d3d
Create Date: 2026-01-09 10:14:20.971924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a9aff11f69'
down_revision: Union[str, Sequence[str], None] = '350b5abb2d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smes', sa.Column('business_license_path', sa.String(), nullable=True))
    op.add_column('smes', sa.Column('cccd_front_path', sa.String(), nullable=True))
    op.add_column('smes', sa.Column('cccd_back_path', sa.String(), nullable=True))
    op.add_column('smes', sa.Column('portrait_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smes', 'portrait_path')
    op.drop_column('smes', 'cccd_back_path')
    op.drop_column('smes', 'cccd_front_path')
    op.drop_column('smes', 'business_license_path')
    # ### end Alembic commands ###
