"""Add invoices table

Revision ID: a77e8e648372
Revises: 2863034ab9e9
Create Date: 2026-01-08 13:55:26.516860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a77e8e648372'
down_revision: Union[str, Sequence[str], None] = '2863034ab9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sme_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('lookup_code', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('buyer_tax_code', sa.String(length=20), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('file_path_xml', sa.String(), nullable=False),
    sa.Column('file_path_pdf', sa.String(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VERIFIED', 'REJECTED', 'TRADING', 'FINANCED', 'COMPLETED', name='invoicestatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_buyer_tax_code'), 'invoices', ['buyer_tax_code'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_lookup_code'), 'invoices', ['lookup_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_lookup_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_buyer_tax_code'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
