"""Add credit_scores table

Revision ID: d65e3bb041c4
Revises: a1878e5d56a1
Create Date: 2026-01-08 16:31:08.725435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65e3bb041c4'
down_revision: Union[str, Sequence[str], None] = 'a1878e5d56a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='riskgrade'), nullable=False),
    sa.Column('recommended_funding_rate', sa.Float(), nullable=False),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_credit_scores_id'), 'credit_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_scores_id'), table_name='credit_scores')
    op.drop_table('credit_scores')
    # ### end Alembic commands ###
