"""Add invoices table

Revision ID: eb2be1201491
Revises: a77e8e648372
Create Date: 2026-01-08 14:45:12.109416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb2be1201491'
down_revision: Union[str, Sequence[str], None] = 'a77e8e648372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('template_code', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('invoice_serial', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('seller_tax_code', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('xml_file_path', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('pdf_file_path', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('verification_details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('invoices', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.alter_column('invoices', 'buyer_tax_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('invoices', 'buyer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_invoices_lookup_code'), table_name='invoices')
    op.create_index(op.f('ix_invoices_seller_tax_code'), 'invoices', ['seller_tax_code'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.drop_column('invoices', 'file_path_xml')
    op.drop_column('invoices', 'file_path_pdf')
    op.drop_column('invoices', 'lookup_code')
    op.drop_column('invoices', 'serial_number')
    op.drop_column('invoices', 'parsed_data')
    op.drop_column('invoices', 'rejection_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('lookup_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('file_path_pdf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('file_path_xml', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_seller_tax_code'), table_name='invoices')
    op.create_index(op.f('ix_invoices_lookup_code'), 'invoices', ['lookup_code'], unique=False)
    op.alter_column('invoices', 'buyer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoices', 'buyer_tax_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('invoices', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('invoices', 'verification_details')
    op.drop_column('invoices', 'pdf_file_path')
    op.drop_column('invoices', 'xml_file_path')
    op.drop_column('invoices', 'seller_tax_code')
    op.drop_column('invoices', 'invoice_serial')
    op.drop_column('invoices', 'template_code')
    # ### end Alembic commands ###
