"""add_fi_balance

Revision ID: f45f4bd4f7b3
Revises: 87a6d76130fb
Create Date: 2026-01-10 04:33:11.087806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45f4bd4f7b3'
down_revision: Union[str, Sequence[str], None] = '87a6d76130fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_institutions', sa.Column('balance', sa.DECIMAL(precision=18, scale=2), server_default='50000000000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_institutions', 'balance')
    # ### end Alembic commands ###
